gatsby/README.md, gatsby/gatsby-config.js, gatsby/plugins/gatsby-source-bnf/README.md, gatsby/plugins/gatsby-source-bnf/src/downloader/downloader.test.ts, gatsby/plugins/gatsby-source-bnf/src/downloader/downloader.ts, gatsby/plugins/gatsby-source-bnf/src/gatsby-node.test.ts, gatsby/plugins/gatsby-source-bnf/src/gatsby-node.ts
https://nicedigital.atlassian.net/browse/BNF-1208
=> BNF-1208 Add feed details

gatsby/plugins/gatsby-source-bnf/src/field-extensions/html.test.ts, gatsby/plugins/gatsby-source-bnf/src/field-extensions/html.ts, package-lock.json, package.json
https://nicedigital.atlassian.net/browse/BNF-1229
=> BNF-1229 Replace xrefs with anchors

functional-tests/features/dentalPractitionersFormulary.feature, functional-tests/support/pagePaths.ts, gatsby/plugins/gatsby-source-bnf/src/downloader/types.ts, gatsby/plugins/gatsby-source-bnf/src/gatsby-node.test.ts, gatsby/plugins/gatsby-source-bnf/src/gatsby-node.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/__snapshots__/index.test.ts.snap, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/dental-practitioners-formulary.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/index.ts, gatsby/plugins/gatsby-source-bnf/src/mock-feed.json, gatsby/plugins/gatsby-source-bnf/src/node-types.ts, gatsby/src/components/DetailsPageLayout/DetailsPageLayout.test.tsx, gatsby/src/components/DetailsPageLayout/DetailsPageLayout.tsx, gatsby/src/components/DetailsPageLayout/__snapshots__/DetailsPageLayout.test.tsx.snap, gatsby/src/pages/dental-practitioners-formulary/__snapshots__/index.test.tsx.snap, gatsby/src/pages/dental-practitioners-formulary/index.test.tsx, gatsby/src/pages/dental-practitioners-formulary/index.tsx, gatsby/src/pages/index.tsx
https://nicedigital.atlassian.net/browse/BNF-1182
=> BNF-1182 Add Dental Practitioners’ Formulary page

gatsby/package-lock.json, gatsby/package.json, gatsby/plugins/gatsby-source-bnf/src/node-creation/interactions.ts, gatsby/src/components/AtoZListPage/AtoZListPage.tsx, gatsby/src/pages/drugs/__snapshots__/index.test.tsx.snap, gatsby/src/pages/interactions/__snapshots__/index.test.tsx.snap, gatsby/src/pages/treatment-summaries/__snapshots__/index.test.tsx.snap
https://nicedigital.atlassian.net/browse/BNF-1205
https://nicedigital.atlassian.net/browse/BNF-1206
https://nicedigital.atlassian.net/browse/BNF-1213
=> BNF-1205 A-Z component integration: drugs, interactions, treatment summaries

functional-tests/features/aboutDetailsPages.feature, functional-tests/features/medicinesGuidanceDetailsPage.feature, functional-tests/features/medicinesGuidanceIndex.feature, functional-tests/steps/then.ts, functional-tests/support/pagePaths.ts, gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/MedicinesGuidanceMenu/MedicinesGuidanceMenu.test.tsx, gatsby/src/components/MedicinesGuidanceMenu/MedicinesGuidanceMenu.tsx, gatsby/src/components/SEO/SEO.tsx, gatsby/src/components/SEO/__snapshots__/SEO.test.tsx.snap, gatsby/src/hooks/useMedicinesGuidancePages.test.ts, gatsby/src/hooks/useMedicinesGuidancePages.ts, gatsby/src/pages/about/__tests__/__snapshots__/{BnfAboutSection.slug}.test.tsx.snap, gatsby/src/pages/about/__tests__/{BnfAboutSection.slug}.test.tsx, gatsby/src/pages/about/{BnfAboutSection.slug}.meta-descriptions.json, gatsby/src/pages/about/{BnfAboutSection.slug}.tsx, gatsby/src/pages/medicines-guidance/__snapshots__/{BnfGuidance.slug}.test.tsx.snap, gatsby/src/pages/medicines-guidance/index.test.tsx, gatsby/src/pages/medicines-guidance/index.tsx, gatsby/src/pages/medicines-guidance/meta-descriptions.json, gatsby/src/pages/medicines-guidance/{BnfGuidance.slug}.meta-descriptions.json, gatsby/src/pages/medicines-guidance/{BnfGuidance.slug}.test.tsx, gatsby/src/pages/medicines-guidance/{BnfGuidance.slug}.tsx, gatsby/src/styles/global.scss, gatsby/src/utils/types.ts, gatsby/static/web.config
https://nicedigital.atlassian.net/browse/BNF-1185
https://nicedigital.atlassian.net/browse/BNF-1186
=> BNF-1185 & BNF-1186 Medicines guidance pages

gatsby/plugins/gatsby-source-bnf/src/downloader/types.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/__snapshots__/index.test.ts.snap, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/drug.ts, gatsby/plugins/gatsby-source-bnf/src/node-creation/drugs.test.ts, gatsby/plugins/gatsby-source-bnf/src/node-creation/drugs.ts, gatsby/src/components/DrugSections/Constituents/Constituents.test.tsx, gatsby/src/components/DrugSections/Constituents/Constituents.tsx, gatsby/src/components/DrugSections/Constituents/__snapshots__/Constituents.test.tsx.snap, gatsby/src/pages/drugs/{BnfDrug.slug}/__snapshots__/index.test.tsx.snap, gatsby/src/pages/drugs/{BnfDrug.slug}/index.test.tsx, gatsby/src/pages/drugs/{BnfDrug.slug}/index.tsx
https://nicedigital.atlassian.net/browse/BNF-1271
=> BNF-1271 Add constituents section

.eslintignore, .prettierignore, functional-tests/features/drugDetails.feature, functional-tests/features/drugsAtoZ.feature, functional-tests/features/interactionDetails.feature, gatsby/plugins/gatsby-source-bnf/src/downloader/types.ts, gatsby/plugins/gatsby-source-bnf/src/node-creation/nurse-prescribers-formulary.ts, gatsby/tsconfig.json, tsconfig.json
https://nicedigital.atlassian.net/browse/BNF-1274
=> BNF-1274 Fix functional test errors caused by drug capitalisation in feed

gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDose.module.scss, gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDoseContent/IndicationsAndDoseContent.module.scss, gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDoseContent/IndicationsAndDoseContent.test.tsx, gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDoseContent/IndicationsAndDoseContent.tsx
https://nicedigital.atlassian.net/browse/BNF-1259
=> BNF-1259 Extra fields for indications and dose content

gatsby/src/components/DrugSections/NationalFunding/NationalFunding.test.tsx, gatsby/src/components/DrugSections/NationalFunding/NationalFunding.tsx, gatsby/src/components/DrugSections/NationalFunding/NationalFundingContent/NationalFundingContent.module.scss, gatsby/src/components/DrugSections/NationalFunding/NationalFundingContent/NationalFundingContent.test.tsx, gatsby/src/components/DrugSections/NationalFunding/NationalFundingContent/NationalFundingContent.tsx, gatsby/src/components/DrugSections/NationalFunding/NationalFundingContent/__snapshots__/NationalFundingContent.test.tsx.snap, gatsby/src/components/DrugSections/index.ts, gatsby/src/pages/drugs/{BnfDrug.slug}/index.tsx
https://nicedigital.atlassian.net/browse/BNF-1270
=> BNF-1270 National funding/access decisions drug monograph section

gatsby/src/components/Interaction/Interaction.module.scss, gatsby/src/components/Interaction/Interaction.tsx, gatsby/src/components/Interaction/__snapshots__/Interaction.test.tsx.snap, gatsby/src/pages/interactions/__snapshots__/{BnfInteractant.slug}.test.tsx.snap, gatsby/src/pages/interactions/{BnfInteractant.slug}.module.scss
https://nicedigital.atlassian.net/browse/BNF-1289
=> BNF-1289 Update interaction designs following design feedback

gatsby/src/components/SEO/SEO.test.tsx, gatsby/src/components/SEO/SEO.tsx
https://nicedigital.atlassian.net/browse/BNF-1299
=> BNF-1299 Remove title words

gatsby/plugins/gatsby-source-bnf/src/downloader/types.ts
https://nicedigital.atlassian.net/browse/BNF-1304
=> BNF-1304 Add type definitions for layered content

gatsby/plugins/gatsby-source-bnf/src/graphql-schema/__snapshots__/index.test.ts.snap, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/borderline-substances.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/index.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/medical-device.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/wound-management.ts, gatsby/plugins/gatsby-source-bnf/src/node-types.ts
https://nicedigital.atlassian.net/browse/BNF-1305
=> BNF-1305 Add GraphQL schema for layered content

gatsby/src/pages/drugs/{BnfDrug.slug}/index.tsx
https://nicedigital.atlassian.net/browse/BNF-1298
=> BNF-1298 Add data attribute to medicinal forms panel

gatsby/package-lock.json, gatsby/src/pages/interactions/__snapshots__/{BnfInteractant.slug}.test.tsx.snap, gatsby/src/pages/interactions/{BnfInteractant.slug}.test.tsx, gatsby/src/pages/interactions/{BnfInteractant.slug}.tsx
https://nicedigital.atlassian.net/browse/BNF-1291
=> BNF-1291 Interactions pages tracking changes

gatsby/src/components/Accordion/Accordion.module.scss, gatsby/src/components/Accordion/Accordion.test.tsx, gatsby/src/components/Accordion/Accordion.tsx, gatsby/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap, gatsby/src/components/AccordionGroup/AccordionGroup.module.scss, gatsby/src/components/AccordionGroup/AccordionGroup.test.tsx, gatsby/src/components/AccordionGroup/AccordionGroup.tsx, gatsby/src/components/AccordionGroupContext/AccordionGroupContext.tsx, gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDose.test.tsx, gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDose.tsx, gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDoseContent/IndicationsAndDoseContent.test.tsx, gatsby/src/components/DrugSections/IndicationsAndDose/IndicationsAndDoseContent/IndicationsAndDoseContent.tsx, gatsby/src/components/Prep/Prep.tsx, gatsby/src/components/Toggle/Toggle.module.scss, gatsby/src/components/Toggle/Toggle.tsx, gatsby/src/pages/drugs/{BnfDrug.slug}/__snapshots__/medicinal-forms.test.tsx.snap, gatsby/src/pages/drugs/{BnfDrug.slug}/medicinal-forms.tsx, gatsby/src/utils/index.test.ts, gatsby/src/utils/index.ts
https://nicedigital.atlassian.net/browse/BNF-1306
=> BNF-1306 Add accordion groups

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1320
=> BNF-1320 Bump nds version nav padding and page pre header weight

gatsby/src/components/AtoZListPage/AtoZListPage.tsx, gatsby/src/components/DrugSections/DrugsInClass/DrugsInClass.tsx, gatsby/src/pages/about/index.tsx, gatsby/src/pages/drugs/__snapshots__/index.test.tsx.snap, gatsby/src/pages/drugs/{BnfDrug.slug}/index.tsx, gatsby/src/pages/interactions/__snapshots__/index.test.tsx.snap, gatsby/src/pages/medical-devices/index.tsx, gatsby/src/pages/medical-devices/{BnfMedicalDevice.slug}.tsx, gatsby/src/pages/medicines-guidance/index.tsx, gatsby/src/pages/nurse-prescribers-formulary/__snapshots__/index.test.tsx.snap, gatsby/src/pages/nurse-prescribers-formulary/index.tsx, gatsby/src/pages/treatment-summaries/__snapshots__/index.test.tsx.snap
https://nicedigital.atlassian.net/browse/BNF-1335
=> BNF-1335 Add data tracking attr for interactions

gatsby/src/components/DetailsPageLayout/DetailsPageLayout.test.tsx, gatsby/src/pages/borderline-substances/{BnfBorderlineSubstancesTaxonomyProductGroup.taxonomy__rootTaxonomy__slug}/{BnfBorderlineSubstancesTaxonomyProductGroup.taxonomy__slug}.test.tsx, gatsby/src/pages/borderline-substances/{BnfBorderlineSubstancesTaxonomyProductGroup.taxonomy__rootTaxonomy__slug}/{BnfBorderlineSubstancesTaxonomyProductGroup.taxonomy__slug}.tsx, gatsby/src/pages/medical-devices/{BnfMedicalDeviceType.medicalDevice__slug}/{BnfMedicalDeviceType.slug}.tsx, gatsby/src/pages/wound-management/index.tsx, gatsby/src/pages/wound-management/{BnfWoundManagementTaxonomy.slug}/index.tsx
Also linting.
https://nicedigital.atlassian.net/browse/BNF-1330
=> BNF-1330 Add meta descriptions to borderline substance product pages.

gatsby/src/components/Interaction/Interaction.module.scss, gatsby/src/components/Interaction/Interaction.tsx, gatsby/src/components/Interaction/__snapshots__/Interaction.test.tsx.snap, gatsby/src/pages/interactions/__snapshots__/{BnfInteractant.slug}.test.tsx.snap
https://nicedigital.atlassian.net/browse/BNF-1348
=> BNF-1348 Render severe text in red

gatsby/plugins/gatsby-source-bnf/src/downloader/types.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/__snapshots__/index.test.ts.snap, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/prep.ts, gatsby/src/components/Prep/Prep.test.tsx, gatsby/src/components/Prep/Prep.tsx, gatsby/src/graphql-fragments/FullPrep.ts, gatsby/src/pages/medical-devices/{BnfClinicalMedicalDeviceInformationGroup.medicalDeviceType__medicalDevice__slug}/{BnfClinicalMedicalDeviceInformationGroup.slug}.test.tsx
https://nicedigital.atlassian.net/browse/BNF-1343
=> BNF-1343 Add ACBS label

gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/Menu/Menu.test.tsx, gatsby/src/components/Menu/Menu.tsx, gatsby/src/pages/about/__tests__/__snapshots__/guidance-for-cautionary-and-advisory-labels.test.tsx.snap, gatsby/src/pages/about/__tests__/__snapshots__/labels.test.tsx.snap, gatsby/src/pages/about/__tests__/__snapshots__/{BnfAboutSection.slug}.test.tsx.snap, gatsby/src/pages/borderline-substances/__snapshots__/index.test.tsx.snap, gatsby/src/pages/borderline-substances/__snapshots__/{BnfBorderlineSubstancesTaxonomyRoot.slug}.test.tsx.snap, gatsby/src/pages/medicines-guidance/__snapshots__/{BnfGuidance.slug}.test.tsx.snap, gatsby/src/pages/nurse-prescribers-formulary/__snapshots__/{BnfNursePrescribersFormularyIntroduction.slug}.test.tsx.snap, gatsby/src/pages/nurse-prescribers-formulary/__snapshots__/{BnfNursePrescribersFormularyTreatmentSummary.slug}.test.tsx.snap, gatsby/src/pages/wound-management/__snapshots__/index.test.tsx.snap, gatsby/src/pages/wound-management/{BnfWoundManagementTaxonomyRoot.taxonomy__slug}/__snapshots__/index.test.tsx.snap
https://nicedigital.atlassian.net/browse/BNF-1352
=> BNF-1352 Remove tags from mobile menu

gatsby/plugins/gatsby-source-bnf/src/downloader/types.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/__snapshots__/index.test.ts.snap, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/medical-device.ts, gatsby/plugins/gatsby-source-bnf/src/node-creation/medical-devices.ts, gatsby/src/pages/medical-devices/{BnfMedicalDeviceType.medicalDevice__slug}/__snapshots__/{BnfMedicalDeviceType.slug}.test.tsx.snap, gatsby/src/pages/medical-devices/{BnfMedicalDeviceType.medicalDevice__slug}/{BnfMedicalDeviceType.slug}.test.tsx, gatsby/src/pages/medical-devices/{BnfMedicalDeviceType.medicalDevice__slug}/{BnfMedicalDeviceType.slug}.tsx
https://nicedigital.atlassian.net/browse/BNF-1345
=> BNF-1345 Added indications and dose to medical device type page

gatsby/src/components/IEBanner/IEBanner.module.scss, gatsby/src/components/IEBanner/IEBanner.test.tsx, gatsby/src/components/IEBanner/IEBanner.tsx, gatsby/src/components/IEBanner/__snapshots__/IEBanner.test.tsx.snap, gatsby/src/components/Layout/Layout.test.tsx, gatsby/src/components/Layout/Layout.tsx, gatsby/src/components/Layout/__snapshots__/Layout.test.tsx.snap
https://nicedigital.atlassian.net/browse/BNF-1356
=> BNF-1356 Add IE11 warning banner

gatsby/src/pages/about/{BnfAboutSection.slug}.meta-descriptions.json, gatsby/src/pages/interactions/appendix-1-interactions.tsx, gatsby/src/pages/interactions/index.test.tsx, gatsby/src/pages/interactions/index.tsx, gatsby/src/pages/medicines-guidance/{BnfGuidance.slug}.meta-descriptions.json, gatsby/src/pages/medicines-guidance/{BnfGuidance.slug}.test.tsx, gatsby/src/pages/nurse-prescribers-formulary/{BnfNursePrescribersFormularyTreatmentSummary.slug}.meta-descriptions.json
https://nicedigital.atlassian.net/browse/BNF-1353
=> BNF-1353 Updates to meta descriptions

gatsby/src/components/IEBanner/IEBanner.tsx, gatsby/src/components/IEBanner/__snapshots__/IEBanner.test.tsx.snap
https://nicedigital.atlassian.net/browse/BNF-1355
=> BNF-1355 IE banner snapshot fix

gatsby/src/pages/about/{BnfAboutSection.slug}.meta-descriptions.json
https://nicedigital.atlassian.net/browse/BNF-1355
=> BNF-1355 Update page slug following feed update

gatsby/package-lock.json, gatsby/package.json, gatsby/plugins/gatsby-source-bnf/src/gatsby-node.ts, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/__snapshots__/index.test.ts.snap, gatsby/plugins/gatsby-source-bnf/src/graphql-schema/drug.ts, gatsby/plugins/gatsby-source-bnf/src/node-creation/drugs.test.ts, gatsby/plugins/gatsby-source-bnf/src/node-creation/drugs.ts, gatsby/src/components/DrugSections/RelatedTreatmentSummaries/RelatedTreatmentSummaries.test.tsx, gatsby/src/components/DrugSections/RelatedTreatmentSummaries/RelatedTreatmentSummaries.tsx, gatsby/src/pages/drugs/{BnfDrug.slug}/__snapshots__/index.test.tsx.snap, gatsby/src/pages/drugs/{BnfDrug.slug}/index.test.tsx, gatsby/src/pages/drugs/{BnfDrug.slug}/index.tsx
https://nicedigital.atlassian.net/browse/BNF-1057
https://nicedigital.atlassian.net/browse/BNF-1368
=> BNF-1057 BNF-1368 Add related NPF treatment summaries to drugs and bump Global Nav

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1377
=> BNF-1377 Fix grid regression

gatsby/src/components/SEO/SEO.tsx, gatsby/src/components/SEO/__snapshots__/SEO.test.tsx.snap
https://nicedigital.atlassian.net/browse/BNF-1372
=> BNF-1372 Update meta description

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1376
=> BNF-1376 Bump global nav to latest

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1386
=> BNF-1386 GN version bump

gatsby/static/web.config
Remove the ref=switch query param from site switch redirects.
Whils retaining additional query params
https://nicedigital.atlassian.net/browse/BNF-1396
=> BNF-1396 Fix site switch redirect

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1407
=> BNF-1407 Bump global nav version

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1408
=> BNF-1408 GN version bump

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1411
=> BNF-1411-global-nav-scrim-not-hiding

functional-tests/docker-compose.yml, gatsby/src/pages/wound-management/{BnfWoundManagementTaxonomyRoot.taxonomy__slug}/index.tsx
https://nicedigital.atlassian.net/browse/BNF-1426
=> BNF-1426 Do not render link to child-slug for lymphoedema-garments

gatsby/src/pages/interactions/{BnfInteractant.slug}.test.tsx, gatsby/src/pages/interactions/{BnfInteractant.slug}.tsx
https://nicedigital.atlassian.net/browse/BNF-1442
=> BNF-1442 Fix filtered interactions when whitespace is present

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1446
=> BNF-1446 GN Master bump commit

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1448
=> BNF-1448 Bump global nav

functional-tests/docker-dev.sh, functional-tests/features/drugsAtoZ.feature, functional-tests/features/header.feature, functional-tests/features/medicalDevicesDetailsPages.feature, functional-tests/features/searchPage.feature, functional-tests/package-lock.json, functional-tests/package.json, functional-tests/tsconfig.json, functional-tests/wdio.conf.ts
https://nicedigital.atlassian.net/browse/BNF-1451
=> BNF-1451 Revert wdio version 8 upgrade on functional tests

gatsby/src/pages/nurse-prescribers-formulary/{BnfNursePrescribersFormularyTreatmentSummary.slug}.meta-descriptions.json
https://nicedigital.atlassian.net/browse/BNF-1471
=> BNF-1471 Update ear wax meta slug

functional-tests/README.md, functional-tests/features/borderlineSubstancesIntroduction.feature, functional-tests/features/borderlineSubstancesRootTaxonomy.feature, functional-tests/features/treatmentSummaryDetails.feature, functional-tests/features/woundManagementIndex.feature, functional-tests/features/woundManagementProduct.feature, functional-tests/features/woundManagementTaxonomy.feature, functional-tests/package-lock.json, functional-tests/package.json, functional-tests/support/action/acceptEULA.ts, functional-tests/support/action/waitForReact.ts, functional-tests/support/pagePaths.ts, functional-tests/wdio.conf.ts
https://nicedigital.atlassian.net/browse/BNF-1476
=> BNF-1476-Functional-tests-failing-on-TeamCity

functional-tests/features/cookiesEULA.feature, functional-tests/steps/then.ts, functional-tests/steps/when.ts, functional-tests/support/action/cookiesToggle.ts, gatsby/src/components/EULABanner/EULABanner.test.tsx, gatsby/src/components/EULABanner/EULABanner.tsx, gatsby/src/components/EULABanner/__snapshots__/EULABanner.test.tsx.snap
https://nicedigital.atlassian.net/browse/BNF-1477
=> BNF-1477 Debug cookie eula interaction

gatsby/src/components/AtoZListPage/AtoZListPage.test.tsx, gatsby/src/components/AtoZListPage/AtoZListPage.tsx, gatsby/src/components/InteractionsAlert/InteractionsAlert.module.scss, gatsby/src/components/InteractionsAlert/InteractionsAlert.test.tsx, gatsby/src/components/InteractionsAlert/InteractionsAlert.tsx, gatsby/src/pages/interactions/__snapshots__/index.test.tsx.snap, gatsby/src/pages/interactions/__snapshots__/{BnfInteractant.slug}.test.tsx.snap, gatsby/src/pages/interactions/index.test.tsx, gatsby/src/pages/interactions/{BnfInteractant.slug}.module.scss, gatsby/src/pages/interactions/{BnfInteractant.slug}.test.tsx, gatsby/src/pages/interactions/{BnfInteractant.slug}.tsx
https://nicedigital.atlassian.net/browse/BNF-1490
=> BNF-1490 create information section for interactions pages on bnf bnfc

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1499
=> BNF-1499 Bump commit global nav

gatsby/package-lock.json, gatsby/package.json
https://nicedigital.atlassian.net/browse/BNF-1501
=> BNF-1501-global-nav-bump-commit-add-link-to-about-tab-in-meganav

gatsby/package-lock.json, gatsby/package.json, gatsby/src/components/SiteHeader/SiteHeader.test.tsx
https://nicedigital.atlassian.net/browse/BNF-1514
Bump commit for GN-233
=> BNF-1514 update global nav to rejigged version

gatsby/gatsby-browser.tsx, gatsby/src/components/AtoZListPage/AtoZListPage.tsx
https://nicedigital.atlassian.net/browse/BNF-1482
=> BNF-1482 investigate focus order 2 bnf
